image: debian:jessie

test:
  script:
    - apt update && apt install -yq curl
    - curl https://packages.chef.io/files/stable/chefdk/1.3.43/debian/8/chefdk_1.3.43-1_amd64.deb -o /tmp/chefdk.deb
    - dpkg -i /tmp/chefdk.deb
    - chef exec rspec
