# This file uses Test Kitchen with the kitchen-dokken driver to
# perform functional testing. Doing so requires that your runner be a
# Docker runner configured for privileged mode. Please see
# https://docs.gitlab.com/runner/executors/docker.html#use-docker-in-docker-with-privileged-mode
# for help configuring your runner properly, or, if you want to switch
# to a different driver, see http://kitchen.ci/docs/drivers

image: "chef/chefdk"
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  KITCHEN_LOCAL_YAML: .kitchen.yml
  CHEF_LICENSE: accept-no-persist

stages:
  - lint
  - unit
  - functional

cookstyle:
  stage: lint
  script:
  - chef exec cookstyle .

chefspec:
  stage: unit
  script:
  - chef exec rspec
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml

# Set up your test matrix here. Example:
#verify-centos-6:
#  stage: functional
#  before_script:
#  - apt-get update
#  - apt-get -y install rsync
#  script:
#  - kitchen verify default-centos-6 --destroy=always
#  
#verify-centos-7:
integration_test:
  stage: functional
  before_script:
    - chef --version
  script:
  - chef exec kitchen test 

