driver:
  name: dokken
  privileged: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  chef_license: accept
  product_name: chef
  product_version: 15

verifier:
  name: inspec

platforms:
  - name: ubuntu

transport:
  name: dokken

suites:
  - name: default
    run_list:
      - recipe[org_base::default]
    verifier:
      inspec_tests:
        - test/integration/default # TODO
    attributes:
      group: 'everybody'
      user: 'test'
      hello: true



